### PR TITLE
Structure

### PR DESCRIPTION
**Pull request by fedgut**
Create a basic project structure:
-Removed bundled files and assets
-Added linters and config files
-Created a Heroku app for CI-CD

### CODE REVIEW

**Comment by shshamim63** [comment]
## Status :recycle: Changes Required :recycle: 
___
Hi @fedgut :wave: 
I can see the Big.js and propType package. But your linter is not functional. I can not see the status/check of linter.
image
Are you sure, you have followed all the instructions given in this [link](https://github.com/microverseinc/linters-config/tree/master/react-redux). I was not able to run eslint on my local dev too. Take a look at the [eslint config](https://github.com/microverseinc/linters-config/blob/master/react-redux/.eslintrc.json) too. 
- I don't think that you need tests for your components now. And It is better to enclose your css into a separate folder naming style.
___
#### Once you resolve the issues please send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

**Comment by fedgut** [comment]
Hello! So, which eslint instructions should I follow? Both are from Microverse, for react/redux and are conflicting instructions. 

https://github.com/microverseinc/linters-config/tree/master/react-redux
https://github.com/microverseinc/linters-config/tree/Stickler/react-redux

**Comment by fedgut** [comment]
Linters

**Review by bellom — APPROVED** [review]
## Hi @fedgut   :clap: 

**Great work making all the necessary corrections from the previous review.**

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Pull request merged**
